name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "github-actions"

          git remote add space https://vschauhan0:$HF_TOKEN@huggingface.co/spaces/vschauhan0/movies-recomandation-system

          git push --force space main
